// src/Terms.jsx
export default function Terms({ onBack, theme, D, glassCard, textPrimary, textSecondary, textMuted }) {
  const sections = [
    {
      title: "1. Acceptance of Terms",
      body: "By accessing or using Spider Resume, you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the service.",
    },
    {
      title: "2. Use of Service",
      body: "Users may create, edit, and manage resumes using the Spider Resume platform. The service is provided for personal, non-commercial resume creation purposes.",
    },
    {
      title: "3. User Responsibilities",
      body: "You are responsible for ensuring that all information you enter into Spider Resume is accurate, truthful, and lawful. You must not misrepresent your qualifications, experience, or identity in any resume created using this platform.",
    },
    {
      title: "4. Prohibited Activities",
      bullets: [
        "Misuse the service or attempt to circumvent usage limits",
        "Upload or enter harmful, illegal, or offensive content",
        "Attempt to disrupt, hack, or reverse-engineer the platform",
        "Create multiple accounts to bypass free-tier restrictions",
        "Resell or sublicense access to Spider Resume",
      ],
    },
    {
      title: "5. Intellectual Property",
      body: "The Spider Resume platform — including its design, code, branding, and AI prompts — is the intellectual property of the project owner. Resume content you create remains your own property. You may not copy, redistribute, or reproduce any part of the platform without written permission.",
    },
    {
      title: "6. Free & Pro Plans",
      body: "Free users receive 1 AI resume generation per day. Pro users receive unlimited generations, all templates, and an ad-free experience. Subscriptions are billed monthly (₹99/month) or as a one-time lifetime purchase (₹499). All payments are final and non-refundable unless required by law.",
    },
    {
      title: "7. Service Changes",
      body: "Spider Resume reserves the right to modify, update, or discontinue any feature at any time. We will make reasonable efforts to notify users of significant changes. Continued use of the platform after updates constitutes your acceptance of the revised service.",
    },
    {
      title: "8. Limitation of Liability",
      body: "Spider Resume is provided on an 'as is' basis. We make no warranties regarding job placement, interview success, or resume effectiveness. We are not liable for any indirect, incidental, or consequential damages arising from your use or misuse of the platform.",
    },
    {
      title: "9. AI-Generated Content",
      body: "Resume content generated by AI is provided as a starting point. You are responsible for reviewing, verifying, and editing all AI-generated content before submitting to employers.",
    },
    {
      title: "10. Contact",
      contact: "contact@spiderresume.com",
    },
  ];

  return (
    <div style={{ maxWidth: "720px", margin: "0 auto", padding: "40px 24px 80px" }}>
      <button onClick={onBack} style={{ background: "none", border: "none", cursor: "pointer", color: textMuted, fontSize: "13px", marginBottom: "28px", padding: 0 }}>← Back</button>

      <h1 style={{ fontSize: "32px", fontWeight: "800", color: textPrimary, margin: "0 0 6px" }}>Terms & Conditions</h1>
      <p style={{ fontSize: "12px", color: textMuted, margin: "0 0 32px" }}>Last updated: March 2026</p>

      <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
        {sections.map(({ title, body, bullets, contact }) => (
          <div key={title} style={{ ...glassCard, padding: "22px 26px" }}>
            <p style={{ fontSize: "13px", fontWeight: "700", color: textPrimary, margin: "0 0 10px", letterSpacing: "0.01em" }}>{title}</p>
            {body && <p style={{ fontSize: "13px", color: textSecondary, lineHeight: 1.75, margin: 0 }}>{body}</p>}
            {bullets && (
              <ul style={{ margin: 0, paddingLeft: "18px", display: "flex", flexDirection: "column", gap: "5px" }}>
                {bullets.map(b => <li key={b} style={{ fontSize: "13px", color: textSecondary, lineHeight: 1.7 }}>{b}</li>)}
              </ul>
            )}
            {contact && (
              <a href={`mailto:${contact}`} style={{ fontSize: "13px", color: theme.accent1, fontWeight: "600", textDecoration: "none" }}>{contact}</a>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
